"use client";
import { useState } from "react";
import { Check, ExternalLink, X } from "lucide-react";
import { Button } from "@/components/ui/button";
type Screen = { eyebrow: string; heading: string; body: string; action: string };
export function IterationPreview({ proposal, onDecision }: { proposal: { title: string; summary: string; before: Screen; after: Screen }; onDecision: (decision: "approved" | "denied") => void }) {
  const [decision, setDecision] = useState<"approved" | "denied" | null>(null); const decide = (next: "approved" | "denied") => { setDecision(next); onDecision(next); };
  return <section className="flex min-h-0 flex-1 flex-col bg-[#f5f5f3]"><div className="border-b border-zinc-200 bg-white/75 px-5 py-5 backdrop-blur-xl sm:px-7"><p className="text-xs font-semibold uppercase tracking-[.13em] text-zinc-500">Proposed iteration</p><div className="mt-2 flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold tracking-tight text-zinc-900">{proposal.title}</h2><p className="mt-1 text-sm leading-5 text-zinc-500">{proposal.summary}</p></div><button className="rounded-lg p-2 text-zinc-500 hover:bg-zinc-100" aria-label="Open preview"><ExternalLink className="size-4" /></button></div></div><div className="grid flex-1 content-center gap-4 p-5 lg:grid-cols-2 lg:p-7"><FeatureCard screen={proposal.before} muted /><FeatureCard screen={proposal.after} /></div><div className="border-t border-zinc-200 bg-white/80 p-5 backdrop-blur-xl sm:flex sm:items-center sm:justify-between sm:px-7"><p className="mb-3 text-sm text-zinc-500 sm:mb-0">{decision === "approved" ? "Approved — this will become the next test target." : decision === "denied" ? "Denied — the feedback remains in the loop history." : "Approve only if this addresses the feedback above."}</p>{!decision && <div className="flex gap-2"><Button variant="outline" onClick={() => decide("denied")} className="rounded-lg border-zinc-300 bg-white text-zinc-700"><X className="size-4" /> Deny</Button><Button onClick={() => decide("approved")} className="rounded-lg bg-zinc-900 text-white hover:bg-zinc-700"><Check className="size-4" /> Approve iteration</Button></div>}</div></section>;
}
function FeatureCard({ screen, muted = false }: { screen: Screen; muted?: boolean }) { return <article className={`overflow-hidden rounded-2xl border ${muted ? "border-zinc-200 bg-white" : "border-emerald-200 bg-white shadow-[0_12px_40px_rgb(21_128_61/10%)]"}`}><div className={`flex items-center justify-between border-b px-4 py-3 ${muted ? "border-zinc-100" : "border-emerald-100"}`}><span className={`text-xs font-semibold ${muted ? "text-zinc-400" : "text-emerald-700"}`}>{screen.eyebrow}</span><span className="flex gap-1"><i className="size-1.5 rounded-full bg-zinc-200" /><i className="size-1.5 rounded-full bg-zinc-200" /><i className="size-1.5 rounded-full bg-zinc-200" /></span></div><div className="p-6 sm:p-8"><div className={`mb-6 size-9 rounded-lg ${muted ? "bg-zinc-100" : "bg-emerald-100"}`} /><h3 className="max-w-[15rem] text-2xl font-semibold leading-7 tracking-tight text-zinc-900">{screen.heading}</h3><p className="mt-3 max-w-[17rem] text-sm leading-6 text-zinc-500">{screen.body}</p><button className={`mt-7 rounded-lg px-3.5 py-2 text-sm font-semibold ${muted ? "bg-zinc-100 text-zinc-600" : "bg-zinc-900 text-white"}`}>{screen.action}</button></div></article>; }
